---
- hosts: all
  tasks:
    - package:   
        name: "hadoop" 
        state: present
    - package:   
        name: "jdk" 
        state: present
    - copy:
        src: "../files/hdfs-site.xml"
        dest: "/etc/hadoop/hdfs-site.xml"
    - copy:
        src: "../temp/core-site.xml"
        dest: "/etc/hadoop/core-site.xml"

    - copy:
        src: "../temp/mapred-site.xml"
        dest: "/etc/hadoop/mapred-site.xml"
    
    - command: hadoop-daemon.sh start datanode

    - command: hadoop-daemon.sh start tasktracker

    - command: hadoop dfsadmin -safemode leave
