---
- hosts: hostname
  tasks:
     - package:   
        name: "hadoop" 
        state: present
     - package:   
        name: "jdk" 
        state: present
     - copy:
        src: "/webcontent/temp/hdfs-siteNUMBER.xml"
        dest: "/etc/hadoop/hdfs-site.xml"
     - copy:
        src: "/webcontent/temp/core-siteNUMBER.xml"
        dest: "/etc/hadoop/core-site.xml"
     - copy:
        src: "/webcontent/temp/mapred-siteNUMBER.xml"
        dest: "/etc/hadoop/mapred-site.xml"


              
              
           
    
